### ISSUE TITLE
[Bug] DISPLAY_NAME column is null

### ISSUE THREAD

**Issue by nate-moo** [yukino-app/yukino#165]
**Describe the bug**
Unable to install latest Android APK on Android 12

**To Reproduce**
Download APK
Install APK

**Expected behavior**
App to be installed

**Screenshots**
![Screenshot_20211124-111619](https://user-images.githubusercontent.com/40650681/143275614-16be9f6c-8cd8-4259-bbe4-0a74448054fc.png)

**Environment (please complete the following information):**

-   OS: Android 12
-   Version: V1.0.10-beta0

**Additional context**

<details>
  <summary>Logs</summary>
  Rooted installer error:

 Device: google Pixel 6 | Not MIUI | Android 12 | Using FilterApkSource ApkSource implementation | SAI 4.5

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkName(DefaultApkSource.java:42)
	at com.aefyr.sai.model.apksource.SignerApkSource.getApkName(SignerApkSource.java:64)
	at com.aefyr.sai.model.apksource.SignerApkSource.nextApk(SignerApkSource.java:46)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:25)
	at com.aefyr.sai.installer2.impl.shell.ShellSaiPackageInstaller.install(ShellSaiPackageInstaller.java:112)
	at com.aefyr.sai.installer2.impl.shell.ShellSaiPackageInstaller.lambda$enqueueSession$0$ShellSaiPackageInstaller(ShellSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.shell.-$$Lambda$ShellSaiPackageInstaller$VdI3y9AkULdYCG2o9afJnUCfQnA.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

  
  
</details>
 
 ## Checklist
 -   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
Has been fixed in dev but it's not released yet. You can install preview build for now: https://www.dropbox.com/s/k3q8tqcjrezki57/Yukino_v1.0.11-beta.0-android.apk?dl=0

**Comment by nate-moo** [comment]
That worked, thanks!
